/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipRouteImport } from './routes/tip'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as PayRouteImport } from './routes/pay'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TipSlugRouteImport } from './routes/tip.$slug'

const TipRoute = TipRouteImport.update({
  id: '/tip',
  path: '/tip',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TipSlugRoute = TipSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/pay': typeof PayRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/tip': typeof TipRouteWithChildren
  '/tip/$slug': typeof TipSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/pay': typeof PayRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/tip': typeof TipRouteWithChildren
  '/tip/$slug': typeof TipSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/dashboard': typeof DashboardRoute
  '/escrow': typeof EscrowRoute
  '/pay': typeof PayRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/tip': typeof TipRouteWithChildren
  '/tip/$slug': typeof TipSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge'
    | '/dashboard'
    | '/escrow'
    | '/pay'
    | '/routes'
    | '/settings'
    | '/tip'
    | '/tip/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge'
    | '/dashboard'
    | '/escrow'
    | '/pay'
    | '/routes'
    | '/settings'
    | '/tip'
    | '/tip/$slug'
  id:
    | '__root__'
    | '/'
    | '/bridge'
    | '/dashboard'
    | '/escrow'
    | '/pay'
    | '/routes'
    | '/settings'
    | '/tip'
    | '/tip/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeRoute: typeof BridgeRoute
  DashboardRoute: typeof DashboardRoute
  EscrowRoute: typeof EscrowRoute
  PayRoute: typeof PayRoute
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRoute
  TipRoute: typeof TipRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tip': {
      id: '/tip'
      path: '/tip'
      fullPath: '/tip'
      preLoaderRoute: typeof TipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tip/$slug': {
      id: '/tip/$slug'
      path: '/$slug'
      fullPath: '/tip/$slug'
      preLoaderRoute: typeof TipSlugRouteImport
      parentRoute: typeof TipRoute
    }
  }
}

interface TipRouteChildren {
  TipSlugRoute: typeof TipSlugRoute
}

const TipRouteChildren: TipRouteChildren = {
  TipSlugRoute: TipSlugRoute,
}

const TipRouteWithChildren = TipRoute._addFileChildren(TipRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeRoute: BridgeRoute,
  DashboardRoute: DashboardRoute,
  EscrowRoute: EscrowRoute,
  PayRoute: PayRoute,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRoute,
  TipRoute: TipRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
